### PR TITLE
NFC: Better mifare classic dictionary

### PR DESCRIPTION
**Pull request by wutchdugsinrl**
# What's new

- [Describe changes here]

-----
# For the reviewer

- [ ] I've uploaded the firmware with this patch to a device and verified its functionality
- [ ] I've confirmed the bug to be fixed / feature to be stable

### CODE REVIEW

**Comment by ZProLegend007** [comment]
Woah... awesome- but uhh... does the flipper have hardware capable enough to use all that information?? It's likely that it would take the flipper waaaaayyyy too long. Perhaps sorting the keys from most likely to be needed to least likely would help but even then that's wayyyy to large a task.

**Comment by wutchdugsinrl** [comment]
hi yes I've tried it and the dictionary had all the keys for all my card

**Comment by Drjacky** [comment]
@Willy-JL I see this PR got merged but why the `dev` still has the [old (small) dict](https://github.com/flipperdevices/flipperzero-firmware/blob/dev/applications/main/nfc/resources/nfc/assets/mf_classic_dict.nfc)?

**Comment by WillyJL** [comment]
@Drjacky we were all hopeful that it would be abundantly clear without further comment that this PR is a joke. A million lines of dictionary attack are useless and stupid, this was done as an inside joke making fun of one particular fake flipper influencer maliciously instructing people on how to waste time and get in legal trouble with huge dictionaries and fuzzing files like this one. I merged it as a joke and then immediately force pushed the branch back to the previous commit.

**Pull request merged**
