### PR TITLE
New (and improved!) "Updating" Icon

### PR DESCRIPTION
**Pull request by the1anonlypr3**
# marvel of art created by a team of (**skilled and unskilled**) artists

-----

<h3> HI WILLY ! </h3>

- As the title suggests, new "updating" logo :)

<i>Concept by Mr.House, original art by Vale, design by Pr3, feedbacks from nescap and @Kuronons <3, Edit/inspiration by @Kuronons :3c</i>

<a href="https://github.com/the1anonlypr3">pr3.</a>
<a href="https://github.com/Kuronons">Kuronons</a>
<h4> everyone else's @s 😭 </h4>

### CODE REVIEW

**Review by dropalltables — APPROVED** [review]

**Comment by dropalltables** [comment]
this would be so cool, please add

**Comment by the1anonlypr3** [comment]
<strong><h1>closing this, refer to new PR.</h1></strong>

**Comment by the1anonlypr3** [comment]
<strong><h1>NEVERMIND LOL I COULD'VE JUST MERGED IT FALSE ALARM, WILLY MERGE THIS 😭 </h1></strong>

**Review by WillyJL — APPROVED** [review]
as i mentioned on discord, 1px wide border just looked too thin next to the thicker text on updating screen. 2px border while yappy is 1px thin is not ideal, but better than thin border IMO, and we can come back to tweak it later :D

either way, very nice work :heart:

**Comment by the1anonlypr3** [comment]
> as i mentioned on discord, 1px wide border just looked too thin next to the thicker text on updating screen. 2px border while yappy is 1px thin is not ideal, but better than thin border IMO, and we can come back to tweak it later :D
> 
> either way, very nice work ❤️

thanks Willy :D! so happy to be apart of Momentum, even if it's something as small as this. thank you so much again man :)

**Pull request merged**
