### PR TITLE
RFID: Add blank InstaFob detection

### PR DESCRIPTION
**Pull request by skyhawkillusions**
# What's new

- Instafobs are based on t5577 chipset, so once rewritten, they are usually readable by Flipper
- Blank InstaFobs however dont contain any data that flipper can understand
- This protocol can detect blank InstaFobs
- Code by @jamisonderek

-----
# For the reviewer

- [x] I've uploaded the firmware with this patch to a device and verified its functionality
- [x] I've confirmed the bug to be fixed / feature to be stable

### CODE REVIEW

**Comment by WillyJL** [comment]
please keep changes between PRs separate

**Comment by WillyJL** [comment]
@skyhawkillusions i edited the PR description with some basic info, please provide atleast some basic detail when proposing a change in the future )

**Review by WillyJL — APPROVED** [review]
LGTM )

**Comment by jerji** [comment]
This could probably be pushed upstream as well so that everyone can take advantage of it

**Comment by skyhawkillusions** [comment]
Agreed

**Pull request merged**
