### PR TITLE
Infrared: Remove duplicates from Projectors universal remote

### PR DESCRIPTION
**Pull request by Wemmy0**
# What's new

Removed more duplicates from the `Projectors.ir` universal remote

-----
# For the reviewer

- [x] I've uploaded the firmware with this patch to a device and verified its functionality
- [x] I've confirmed the bug to be fixed / feature to be stable

### CODE REVIEW

**Comment by Wemmy0** [comment]
Only duplicates removed, nothing missing

Comparing files with python script:
[original projectors.ir](https://github.com/Next-Flip/Momentum-Firmware/blob/4abf3c024ba8cd97ca80a689712e32f933e81f5c/applications/main/infrared/resources/infrared/assets/projectors.ir) | [new projectors.ir](https://github.com/Wemmy0/Momentum-Firmware/blob/a9725fd2344467b6a88f765e10263b0925e85f66/applications/main/infrared/resources/infrared/assets/projectors.ir)
```
Original: 197
New: 196
Only empty line missing

Process finished with exit code 0
```
Script used:
```py
def parse_ir_file(path):
    with open(path, "r") as file:
        data = file.readlines()

    new = list(data)
    for line in data:
        if "name: " in line:
            break
        else:
            new.remove(line)
    return new


def process(ir):
    data = parse_ir_file(ir)
    codes = []
    temp = ()
    for line in data:
        if "#" in line:
            codes.append(temp)
            temp = ()
        else:
            temp += (line,)
    return list(set(codes))


old = process("original projectors.ir")
new = process("new projectors.ir")
print(f"Original: {len(old)}")
print(f"New: {len(new)}")
for i in old:
    if i not in new:
        if i:
            print("#### MISSING ####")
            for l in i:
                print(l, end='')
        else:
            print("Only empty line missing")
```

**Comment by Wemmy0** [comment]
Only duplicates removed, nothing missing

Comparing files with python script:
[original projectors.ir](https://github.com/Next-Flip/Momentum-Firmware/blob/4abf3c024ba8cd97ca80a689712e32f933e81f5c/applications/main/infrared/resources/infrared/assets/projectors.ir) | [new projectors.ir](https://github.com/Wemmy0/Momentum-Firmware/blob/a9725fd2344467b6a88f765e10263b0925e85f66/applications/main/infrared/resources/infrared/assets/projectors.ir)
```
Original: 197
New: 196
Only empty line missing

Process finished with exit code 0
```
Script used:
```py
def parse_ir_file(path):
    with open(path, "r") as file:
        data = file.readlines()

    new = list(data)
    for line in data:
        if "name: " in line:
            break
        else:
            new.remove(line)
    return new


def process(ir):
    data = parse_ir_file(ir)
    codes = []
    temp = ()
    for line in data:
        if "#" in line:
            codes.append(temp)
            temp = ()
        else:
            temp += (line,)
    return list(set(codes))


old = process("original projectors.ir")
new = process("new projectors.ir")
print(f"Original: {len(old)}")
print(f"New: {len(new)}")
for i in old:
    if i not in new:
        if i:
            print("#### MISSING ####")
            for l in i:
                print(l, end='')
        else:
            print("Only empty line missing")
```

**Comment by Wemmy0** [comment]
Uploaded firmware to flipper and `projectors.ir` all works as expected but significantly faster.
`Power` command gone from taking 48s -> 22s  (122 -> 65 codes)
IMG_7012
IMG_7015

**Review by WillyJL — APPROVED** [review]
Crazy that there were so many duplicates, but it checks out. You missed one at the added section at the top, fixed it.

Thanks!

**Comment by WillyJL** [comment]
@Wemmy0 unleashed developer @xMasterX saw this and told me that duplicated signals are intentional: most projectors require 2 button presses to confirm shutdown. I reverted this PR, and only kept the new codes you had added, of which one is doubled for the same reason

**Comment by Wemmy0** [comment]
Ah that makes a lot of sense and explains why there where so many

**Pull request merged**
